export default [
  'World',
  'USA',
  'Brazil',
  'Russia',
  'UK',
  'Spain',
  'India',
  'Italy',
  'Peru',
  'Germany',
  'Iran',
  'Turkey',
  'France',
  'Chile',
  'Mexico',
  'Pakistan',
  'Saudi Arabia',
  'Canada',
  'Bangladesh',
  'Qatar',
  'Belgium',
  'South Africa',
  'Belarus',
  'Sweden',
  'Netherlands',
  'Ecuador',
  'Colombia',
  'UAE',
  'Singapore',
  'Egypt',
  'Portugal',
  'Indonesia',
  'Kuwait',
  'Switzerland',
  'Ukraine',
  'Poland',
  'Argentina',
  'Ireland',
  'Philippines',
  'Afghanistan',
  'Romania',
  'Dominican Republic',
  'Oman',
  'Israel',
  'Panama',
  'Japan',
  'Austria',
  'Bahrain',
  'Iraq',
  'Bolivia',
  'Armenia',
  'Nigeria',
  'Kazakhstan',
  'Denmark',
  'Serbia',
  'S. Korea',
  'Algeria',
  'Ghana',
  'Moldova',
  'Czechia',
  'Cameroon',
  'Norway',
  'Morocco',
  'Azerbaijan',
  'Malaysia',
  'Guatemala',
  'Honduras',
  'Australia',
  'Finland',
  'Sudan',
  'Tajikistan',
  'Senegal',
  'Uzbekistan',
  'Nepal',
  'DRC',
  'Djibouti',
  'Guinea',
  'Ivory Coast',
  'Luxembourg',
  'Hungary',
  'Haiti',
  'North Macedonia',
  'Gabon',
  'El Salvador',
  'Thailand',
  'Kenya',
  'Greece',
  'Bulgaria',
  'Bosnia and Herzegovina',
  'Venezuela',
  'Ethiopia',
  'Somalia',
  'Croatia',
  'Mayotte',
  'Cuba',
  'Kyrgyzstan',
  'Estonia',
  'Maldives',
  'CAR',
  'Sri Lanka',
  'Iceland',
  'Lithuania',
  'Mali',
  'South Sudan',
  'Slovakia',
  'New Zealand',
  'Slovenia',
  'Nicaragua',
  'Costa Rica',
  'Lebanon',
  'Guinea-Bissau',
  'Albania',
  'Equatorial Guinea',
  'Mauritania',
  'Madagascar',
  'Paraguay',
  'Zambia',
  'Hong Kong',
  'Latvia',
  'Tunisia',
  'Sierra Leone',
  'Niger',
  'Cyprus',
  'Burkina Faso',
  'French Guiana',
  'Jordan',
  'Andorra',
  'Uruguay',
  'Chad',
  'Georgia',
  'Congo',
  'Diamond Princess',
  'San Marino',
  'Uganda',
  'Malta',
  'Sao Tome and Principe',
  'Cabo Verde',
  'Jamaica',
  'Channel Islands',
  'Yemen',
  'Togo',
  'Tanzania',
  'Réunion',
  'Palestine',
  'Rwanda',
  'Mozambique',
  'Malawi',
  'Taiwan',
  'Liberia',
  'Eswatini',
  'Libya',
  'Mauritius',
  'Isle of Man',
  'Vietnam',
  'Montenegro',
  'Zimbabwe',
  'Benin',
  'Myanmar',
  'Martinique',
  'Mongolia',
  'Faeroe Islands',
  'Cayman Islands',
  'Gibraltar',
  'Guadeloupe',
  'Comoros',
  'Guyana',
  'Syria',
  'Suriname',
  'Bermuda',
  'Brunei',
  'Cambodia',
  'Trinidad and Tobago',
  'Angola',
  'Bahamas',
  'Aruba',
  'Monaco',
  'Barbados',
  'Burundi',
  'Liechtenstein',
  'Sint Maarten',
  'Bhutan',
  'French Polynesia',
  'Botswana',
  'Macao',
  'Saint Martin',
  'Eritrea',
  'Namibia',
  'Gambia',
  'St. Vincent Grenadines',
  'Antigua and Barbuda',
  'Timor-Leste',
  'Grenada',
  'Curaçao',
  'New Caledonia',
  'Belize',
  'Laos',
  'Saint Lucia',
  'Dominica',
  'Fiji',
  'Saint Kitts and Nevis',
  'Falkland Islands',
  'Greenland',
  'Turks and Caicos',
  'Vatican City',
  'Montserrat',
  'Seychelles',
  'MS Zaandam',
  'Western Sahara',
  'British Virgin Islands',
  'Papua New Guinea',
  'Caribbean Netherlands',
  'St. Barth',
  'Lesotho',
  'Anguilla',
  'Saint Pierre Miquelon',
  'China',
]
